name: Update Date in README

on:
  schedule:
    # 使用 cron 表达式设置每天上海时间 8:00
    - cron: '35 1 8 * * *' # UTC 时间是 1 35 0 每天，UTC+8需要加8小时

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update date in README.md
        run: |
          # 获取当前日期，格式为 YYYY-MM-DD
          current_date=$(date +'%Y-%m-%d')
          
          # 使用 sed 替换 README.md 中的日期
          sed -i "s/更新时间 .*/更新时间 $current_date/" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add README.md
          git commit -m "Update date in README.md to $current_date"
          git push
